<?php
	$_product = $block->getProduct();
?>
<div class="product-content-view">
	<ul>
		<li>
			<span><?php echo __('Content') ?></span>
			<p>
				<?php /* @escapeNotVerified */ echo $_product->getData("composition");?>
				
			</p>	
		</li>
		<li>
			<span><?php echo __('Care') ?></span>
			<p class="4">
				<?php /* @escapeNotVerified */ echo $_product->getAttributeText("care_instructions");?>
			</p>
		</li>
		<li>
			<span><?php echo __('Ply') ?></span>
			<p class="4">
				<?php /* @escapeNotVerified */ echo $_product->getData("ply");?>
			</p>
		</li>
		
	</ul>
</div>