
<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$baseUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<?php if($block->customerLoggedIn()): ?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-header-icon')->toHtml(); ?>
		<div class="dropdown">
			<a class="btn-dropdown" data-toggle="dropdown" href="javascript:void(0)">
		        <p class="customer-name"
		              role="link"
		              tabindex="0"
		              data-bind="scope: 'customer'">
		            <?php echo __('Hi') ?>,<span data-bind="text: customer().firstname"></span>
		        </p>
			</a>
			<ul id="dropdown-menu" class="closed">
				<li class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
				    <a class="action compare no-display" title="<?php /* @escapeNotVerified */ echo __('Compare Products') ?>"
				       data-bind="attr: {'href': compareProducts().listUrl}, css: {'no-display': !compareProducts().count}"
				    >
				        <?php /* @escapeNotVerified */ echo __('Compare Products') ?>
				        <span class="counter qty" data-bind="text: compareProducts().countCaption"></span>
				    </a>
				</li>
				<li><a href="<?php echo $block->getbaseURL() ?>wishlist/"><?php echo __('My Wish List') ?></a></li>
				<li><a href="<?php echo $block->getbaseURL() ?>customer/account/"><?php echo __('My Account') ?></a></li>
				<li><a href="<?php echo $block->getbaseURL() ?>customer/account/logout/"><?php echo __('Sign Out') ?></a></li>
			</ul>
		</div>
<script>
   	require(["jquery"], function($){
	  $('.btn-dropdown').click(function(e) {
	    e.stopPropagation();
	    $('#dropdown-menu').toggleClass('open');
	    return $('#dropdown-menu li a').removeClass();
	  });

	  $('#dropdown-menu li a').click(function(e) {
	    $(this).addClass("flash");
	    return $('#dropdown-menu').removeClass('open');
	  });

	  $('html').click(function() {
	    return $('#dropdown-menu').removeClass('open');
	  });
});	
</script>
<?php else : ?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('top-header-icon')->toHtml(); ?>

		<div class="dropdown">
			<a href="<?php echo $block->getBaseURL() ?>customer/account/login/">
				<p><?php echo __('Login/Join') ?></p>
			</a>
		</div>

<?php endif; ?>
