<div class="header-top container">
	<div class="row">
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-top')->toHtml(); ?>
	</div>
</div>
<script>
require(["jquery","Magento_Theme/js/owl-carousel"], function($,Configurable){
    $('.fadeOut ').owlCarousel({
        items: 1,
        autoplay:true,
        loop: true,
        margin: 10,
        nav: true,
    });
    var owl = $(".owl-carousel");
    // add animate.css class(es) to the elements to be animated
    function setAnimation(_elem, _InOut) {
        // Store all animationend event name in a string.
        // cf animate.css documentation
        var animationEndEvent =
            "webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend";

        _elem.each(function() {
            var $elem = $(this);
            var $animationType = "animated " + $elem.data("animation-" + _InOut);

        $elem.addClass($animationType).one(animationEndEvent, function() {
            $elem.removeClass($animationType); // remove animate.css Class at the end of the animations
            });
        });
    }

    // Fired before current slide change
    owl.on("change.owl.carousel", function(event) {
        var $currentItem = $(".owl-item", owl).eq(event.item.index);
        var $elemsToanim = $currentItem.find("[data-animation-out]");
        setAnimation($elemsToanim, "out");
    });

    // Fired after current slide has been changed
    owl.on("changed.owl.carousel", function(event) {
        var $currentItem = $(".owl-item", owl).eq(event.item.index);
        var $elemsToanim = $currentItem.find("[data-animation-in]");
        setAnimation($elemsToanim, "in");
    });
    $('.instagram-default .owl-carousel').owlCarousel({
        loop: true,
        // margin: 10,
        responsiveClass: true,
        autoplay:true,
        // autoplayTimeout:2000,
        nav:true,
        responsive: {
            0: {
                items: 1,
                loop: true,
                nav: true
            },
            768: {
                items: 2,
                loop: true,
                nav: true
            },
            776: {
                items: 6,
                nav: true,
                loop: true,
                margin: 20
            }
        },
    });
});
</script>